//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class AddressSchema_Mapping : EntityTypeConfiguration<AddressSchema>
    {
        public AddressSchema_Mapping()
        {					
    		this.HasKey(t => t.Id);		
    		this.ToTable("AddressSchema");
    		this.Property(t => t.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
    		this.Property(t => t.C_id).HasColumnName("_id");
    		this.Property(t => t.LastSvrUpdateDate).HasColumnName("LastSvrUpdateDate");
    		this.Property(t => t.Address1).HasColumnName("Address1");
    		this.Property(t => t.Address2).HasColumnName("Address2");
    		this.Property(t => t.Suburb).HasColumnName("Suburb").HasMaxLength(50);
    		this.Property(t => t.PostCode).HasColumnName("PostCode").HasMaxLength(20);
    		this.Property(t => t.State).HasColumnName("State").HasMaxLength(50);
    		this.Property(t => t.Country).HasColumnName("Country").HasMaxLength(50);
    		this.Property(t => t.xlon).HasColumnName("xlon");
    		this.Property(t => t.ylat).HasColumnName("ylat");
    	}
    }
}
