//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class AddressSchema
    {
        public AddressSchema()
        {
            this.OrganisationSchemas = new HashSet<OrganisationSchema>();
            this.ProjectSchemas = new HashSet<ProjectSchema>();
            this.ProjectSchemas1 = new HashSet<ProjectSchema>();
            this.UserSchemas = new HashSet<UserSchema>();
        }
    
        public int Id { get; set; }
        public Nullable<System.Guid> C_id { get; set; }
        public Nullable<System.DateTime> LastSvrUpdateDate { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Suburb { get; set; }
        public string PostCode { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<decimal> xlon { get; set; }
        public Nullable<decimal> ylat { get; set; }
    
        public virtual ICollection<OrganisationSchema> OrganisationSchemas { get; set; }
        public virtual ICollection<ProjectSchema> ProjectSchemas { get; set; }
        public virtual ICollection<ProjectSchema> ProjectSchemas1 { get; set; }
        public virtual ICollection<UserSchema> UserSchemas { get; set; }
    }
}
