//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1573
namespace BTek.Data
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BTekEntities : DbContext
    {
        static BTekEntities()
    	{ 
    		Database.SetInitializer<BTekEntities>(null);
    	}
    	
    	public BTekEntities() : base("name=BTekEntities")
        {
        }
    	
    	public BTekEntities(string nameOrConnectionString) : base(nameOrConnectionString)
    	{	
    	}
    
    	public BTekEntities(string nameOrConnectionString, DbCompiledModel model) : base(nameOrConnectionString, model)
    	{
    	}
    
    	public BTekEntities(DbConnection existingConnection, bool contextOwnsConnection) : base(existingConnection, contextOwnsConnection)
    	{
    	}
    
    	public BTekEntities(DbConnection existingConnection, DbCompiledModel model, bool contextOwnsConnection) : base(existingConnection, model, contextOwnsConnection)
    	{
    	}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
    		modelBuilder.Conventions.Remove<IncludeMetadataConvention>();
    		modelBuilder.Configurations.Add(new AddressSchema_Mapping());
    		modelBuilder.Configurations.Add(new EmailSchema_Mapping());
    		modelBuilder.Configurations.Add(new InvitationSchema_Mapping());
    		modelBuilder.Configurations.Add(new LocationSchema_Mapping());
    		modelBuilder.Configurations.Add(new LogBookSchema_Mapping());
    		modelBuilder.Configurations.Add(new LogSchema_Mapping());
    		modelBuilder.Configurations.Add(new MaterialSchema_Mapping());
    		modelBuilder.Configurations.Add(new MemberSchema_Mapping());
    		modelBuilder.Configurations.Add(new OrganisationSchema_Mapping());
    		modelBuilder.Configurations.Add(new ProjectSchema_Mapping());
    		modelBuilder.Configurations.Add(new RoleSchema_Mapping());
    		modelBuilder.Configurations.Add(new ScheduleSchema_Mapping());
    		modelBuilder.Configurations.Add(new ServiceSchema_Mapping());
    		modelBuilder.Configurations.Add(new StageSchema_Mapping());
    		modelBuilder.Configurations.Add(new sysdiagram_Mapping());
    		modelBuilder.Configurations.Add(new TaskSchema_Mapping());
    		modelBuilder.Configurations.Add(new UserScheduleSchema_Mapping());
    		modelBuilder.Configurations.Add(new UserSchema_Mapping());
        }
    	
        public DbSet<AddressSchema> AddressSchemas { get; set; }
        public DbSet<EmailSchema> EmailSchemas { get; set; }
        public DbSet<InvitationSchema> InvitationSchemas { get; set; }
        public DbSet<LocationSchema> LocationSchemas { get; set; }
        public DbSet<LogBookSchema> LogBookSchemas { get; set; }
        public DbSet<LogSchema> LogSchemas { get; set; }
        public DbSet<MaterialSchema> MaterialSchemas { get; set; }
        public DbSet<MemberSchema> MemberSchemas { get; set; }
        public DbSet<OrganisationSchema> OrganisationSchemas { get; set; }
        public DbSet<ProjectSchema> ProjectSchemas { get; set; }
        public DbSet<RoleSchema> RoleSchemas { get; set; }
        public DbSet<ScheduleSchema> ScheduleSchemas { get; set; }
        public DbSet<ServiceSchema> ServiceSchemas { get; set; }
        public DbSet<StageSchema> StageSchemas { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TaskSchema> TaskSchemas { get; set; }
        public DbSet<UserScheduleSchema> UserScheduleSchemas { get; set; }
        public DbSet<UserSchema> UserSchemas { get; set; }
    }
}
