//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class EmailSchema_Mapping : EntityTypeConfiguration<EmailSchema>
    {
        public EmailSchema_Mapping()
        {					
    		this.HasKey(t => t.Id);		
    		this.ToTable("EmailSchema");
    		this.Property(t => t.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
    		this.Property(t => t.C_id).HasColumnName("_id");
    		this.Property(t => t.LastSvrUpdateDate).HasColumnName("LastSvrUpdateDate");
    		this.Property(t => t.To).HasColumnName("To").HasMaxLength(50);
    		this.Property(t => t.Subject).HasColumnName("Subject").HasMaxLength(100);
    		this.Property(t => t.Message).HasColumnName("Message");
    		this.Property(t => t.Status).HasColumnName("Status").HasMaxLength(50);
    		this.Property(t => t.Attachment).HasColumnName("Attachment");
    	}
    }
}
