//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class InvitationSchema
    {
        public int Id { get; set; }
        public System.Guid C_id { get; set; }
        public Nullable<System.DateTime> LastSvrUpdateDate { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> SenderId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string RecipientEmail { get; set; }
        public Nullable<int> RecipientId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<System.DateTime> DateExpires { get; set; }
        public string Message { get; set; }
    
        public virtual MemberSchema MemberSchema { get; set; }
        public virtual OrganisationSchema OrganisationSchema { get; set; }
        public virtual UserSchema UserSchema { get; set; }
        public virtual RoleSchema RoleSchema { get; set; }
        public virtual UserSchema UserSchema1 { get; set; }
    }
}
