//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class LocationSchema
    {
        public int Id { get; set; }
        public System.Guid C_id { get; set; }
        public Nullable<System.DateTime> LastSvrUpdateDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime Recorded { get; set; }
        public string Source { get; set; }
        public Nullable<int> Accuracy { get; set; }
        public Nullable<decimal> Altitude { get; set; }
        public Nullable<decimal> Bearing { get; set; }
        public Nullable<decimal> Speed { get; set; }
        public Nullable<decimal> xlon { get; set; }
        public Nullable<decimal> ylat { get; set; }
    
        public virtual UserSchema UserSchema { get; set; }
    }
}
