//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class LocationSchema_Mapping : EntityTypeConfiguration<LocationSchema>
    {
        public LocationSchema_Mapping()
        {					
    		this.HasKey(t => t.Id);		
    		this.ToTable("LocationSchema");
    		this.Property(t => t.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
    		this.Property(t => t.C_id).HasColumnName("_id");
    		this.Property(t => t.LastSvrUpdateDate).HasColumnName("LastSvrUpdateDate");
    		this.Property(t => t.UserId).HasColumnName("UserId");
    		this.Property(t => t.Recorded).HasColumnName("Recorded");
    		this.Property(t => t.Source).HasColumnName("Source").IsRequired().HasMaxLength(50);
    		this.Property(t => t.Accuracy).HasColumnName("Accuracy");
    		this.Property(t => t.Altitude).HasColumnName("Altitude");
    		this.Property(t => t.Bearing).HasColumnName("Bearing");
    		this.Property(t => t.Speed).HasColumnName("Speed");
    		this.Property(t => t.xlon).HasColumnName("xlon");
    		this.Property(t => t.ylat).HasColumnName("ylat");
    		this.HasOptional(t => t.UserSchema).WithMany(t => t.LocationSchemas).HasForeignKey(d => d.UserId);
    	}
    }
}
