//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class LogBookSchema_Mapping : EntityTypeConfiguration<LogBookSchema>
    {
        public LogBookSchema_Mapping()
        {					
    		this.HasKey(t => t.Id);		
    		this.ToTable("LogBookSchema");
    		this.Property(t => t.Id).HasColumnName("Id");
    		this.Property(t => t.C_id).HasColumnName("_id");
    		this.Property(t => t.LastSvrUpdateDate).HasColumnName("LastSvrUpdateDate");
    		this.Property(t => t.UserId).HasColumnName("UserId");
    		this.Property(t => t.OrgId).HasColumnName("OrgId");
    		this.Property(t => t.ProjectId).HasColumnName("ProjectId");
    		this.Property(t => t.AddressId).HasColumnName("AddressId");
    		this.Property(t => t.Started).HasColumnName("Started");
    		this.Property(t => t.Ended).HasColumnName("Ended");
    		this.Property(t => t.DurationMS).HasColumnName("DurationMS");
    		this.Property(t => t.DistSource).HasColumnName("DistSource");
    		this.Property(t => t.DistTravelled).HasColumnName("DistTravelled");
    		this.Property(t => t.Activity).HasColumnName("Activity").HasMaxLength(100);
    		this.Property(t => t.Confidence).HasColumnName("Confidence");
    		this.Property(t => t.OdometerStart).HasColumnName("OdometerStart");
    		this.Property(t => t.OdometerEnd).HasColumnName("OdometerEnd");
    		this.Property(t => t.IsBusinessRelated).HasColumnName("IsBusinessRelated");
    		this.Property(t => t.Notes).HasColumnName("Notes");
    		this.Property(t => t.Source).HasColumnName("Source");
    		this.Property(t => t.AvgAltitude).HasColumnName("AvgAltitude");
    		this.Property(t => t.MinAltitude).HasColumnName("MinAltitude");
    		this.Property(t => t.MaxAltitude).HasColumnName("MaxAltitude");
    		this.Property(t => t.AvgSpeed).HasColumnName("AvgSpeed");
    		this.Property(t => t.MinSpeed).HasColumnName("MinSpeed");
    		this.Property(t => t.MaxSpeed).HasColumnName("MaxSpeed");
    		this.Property(t => t.AvgAccuracy).HasColumnName("AvgAccuracy");
    		this.Property(t => t.Updates).HasColumnName("Updates");
    		this.Property(t => t.Start_xlon).HasColumnName("Start_xlon");
    		this.Property(t => t.Start_ylon).HasColumnName("Start_ylon");
    		this.Property(t => t.End_xlon).HasColumnName("End_xlon");
    		this.Property(t => t.End_ylon).HasColumnName("End_ylon");
    		this.Property(t => t.Address_Street).HasColumnName("Address_Street").HasMaxLength(100);
    		this.Property(t => t.Address_Suburb).HasColumnName("Address_Suburb").HasMaxLength(100);
    		this.Property(t => t.Address_PostCode).HasColumnName("Address_PostCode").HasMaxLength(100);
    		this.Property(t => t.Address_State).HasColumnName("Address_State").HasMaxLength(100);
    		this.Property(t => t.Address_Country).HasColumnName("Address_Country").HasMaxLength(100);
    		this.HasOptional(t => t.OrganisationSchema).WithMany(t => t.LogBookSchemas).HasForeignKey(d => d.OrgId);
    		this.HasOptional(t => t.ProjectSchema).WithMany(t => t.LogBookSchemas).HasForeignKey(d => d.ProjectId);
    		this.HasOptional(t => t.UserSchema).WithMany(t => t.LogBookSchemas).HasForeignKey(d => d.UserId);
    	}
    }
}
