//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialSchema
    {
        public int Id { get; set; }
        public System.Guid C_id { get; set; }
        public Nullable<System.DateTime> LastSvrUpdateDate { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> StageId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> DeliveryCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> QuotedValue { get; set; }
        public Nullable<bool> IsOrdered { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<bool> ShowOnQuote { get; set; }
    
        public virtual OrganisationSchema OrganisationSchema { get; set; }
        public virtual ProjectSchema ProjectSchema { get; set; }
        public virtual StageSchema StageSchema { get; set; }
    }
}
