//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class MemberSchema
    {
        public MemberSchema()
        {
            this.InvitationSchemas = new HashSet<InvitationSchema>();
        }
    
        public int Id { get; set; }
        public System.Guid C_id { get; set; }
        public System.DateTime LastSvrUpdateDate { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public Nullable<bool> IsOwner { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<InvitationSchema> InvitationSchemas { get; set; }
        public virtual OrganisationSchema OrganisationSchema { get; set; }
        public virtual RoleSchema RoleSchema { get; set; }
        public virtual ScheduleSchema ScheduleSchema { get; set; }
        public virtual UserSchema UserSchema { get; set; }
    }
}
