//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class OrganisationSchema_Mapping : EntityTypeConfiguration<OrganisationSchema>
    {
        public OrganisationSchema_Mapping()
        {					
    		this.HasKey(t => t.Id);		
    		this.ToTable("OrganisationSchema");
    		this.Property(t => t.Id).HasColumnName("Id");
    		this.Property(t => t.C_id).HasColumnName("_id");
    		this.Property(t => t.LastSvrUpdateDate).HasColumnName("LastSvrUpdateDate");
    		this.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(100);
    		this.Property(t => t.OwnerId).HasColumnName("OwnerId");
    		this.Property(t => t.AddressId).HasColumnName("AddressId");
    		this.Property(t => t.AccountType).HasColumnName("AccountType");
    		this.Property(t => t.AccountStatus).HasColumnName("AccountStatus");
    		this.Property(t => t.DateCreated).HasColumnName("DateCreated");
    		this.Property(t => t.DateUpdated).HasColumnName("DateUpdated");
    		this.Property(t => t.DateExpires).HasColumnName("DateExpires");
    		this.HasOptional(t => t.AddressSchema).WithMany(t => t.OrganisationSchemas).HasForeignKey(d => d.AddressId);
    		this.HasOptional(t => t.UserSchema).WithMany(t => t.OrganisationSchemas).HasForeignKey(d => d.OwnerId);
    	}
    }
}
