//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSchema
    {
        public ProjectSchema()
        {
            this.LogBookSchemas = new HashSet<LogBookSchema>();
            this.MaterialSchemas = new HashSet<MaterialSchema>();
            this.TaskSchemas = new HashSet<TaskSchema>();
            this.StageSchemas = new HashSet<StageSchema>();
        }
    
        public int Id { get; set; }
        public System.Guid C_id { get; set; }
        public System.DateTime LastSvrUpdateDate { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Status { get; set; }
        public string CustFirstName { get; set; }
        public string CustLastName { get; set; }
        public string CustEmail { get; set; }
        public string CustPhone { get; set; }
        public Nullable<int> CustAddressId { get; set; }
        public Nullable<int> SiteAddressId { get; set; }
        public Nullable<decimal> QuotedValue { get; set; }
        public Nullable<decimal> QuotedHrs { get; set; }
        public Nullable<decimal> ActualHrs { get; set; }
        public Nullable<decimal> Margin { get; set; }
    
        public virtual AddressSchema AddressSchema { get; set; }
        public virtual AddressSchema AddressSchema1 { get; set; }
        public virtual ICollection<LogBookSchema> LogBookSchemas { get; set; }
        public virtual ICollection<MaterialSchema> MaterialSchemas { get; set; }
        public virtual OrganisationSchema OrganisationSchema { get; set; }
        public virtual ICollection<TaskSchema> TaskSchemas { get; set; }
        public virtual ICollection<StageSchema> StageSchemas { get; set; }
    }
}
