//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class ProjectSchema_Mapping : EntityTypeConfiguration<ProjectSchema>
    {
        public ProjectSchema_Mapping()
        {					
    		this.HasKey(t => t.Id);		
    		this.ToTable("ProjectSchema");
    		this.Property(t => t.Id).HasColumnName("Id");
    		this.Property(t => t.C_id).HasColumnName("_id");
    		this.Property(t => t.LastSvrUpdateDate).HasColumnName("LastSvrUpdateDate");
    		this.Property(t => t.OrgId).HasColumnName("OrgId");
    		this.Property(t => t.CreateDate).HasColumnName("CreateDate");
    		this.Property(t => t.Name).HasColumnName("Name").HasMaxLength(50);
    		this.Property(t => t.Code).HasColumnName("Code").HasMaxLength(50);
    		this.Property(t => t.Status).HasColumnName("Status").HasMaxLength(50);
    		this.Property(t => t.CustFirstName).HasColumnName("CustFirstName").HasMaxLength(50);
    		this.Property(t => t.CustLastName).HasColumnName("CustLastName").HasMaxLength(50);
    		this.Property(t => t.CustEmail).HasColumnName("CustEmail").HasMaxLength(50);
    		this.Property(t => t.CustPhone).HasColumnName("CustPhone").HasMaxLength(50);
    		this.Property(t => t.CustAddressId).HasColumnName("CustAddressId");
    		this.Property(t => t.SiteAddressId).HasColumnName("SiteAddressId");
    		this.Property(t => t.QuotedValue).HasColumnName("QuotedValue");
    		this.Property(t => t.QuotedHrs).HasColumnName("QuotedHrs");
    		this.Property(t => t.ActualHrs).HasColumnName("ActualHrs");
    		this.Property(t => t.Margin).HasColumnName("Margin");
    		this.HasOptional(t => t.AddressSchema).WithMany(t => t.ProjectSchemas).HasForeignKey(d => d.CustAddressId);
    		this.HasOptional(t => t.AddressSchema1).WithMany(t => t.ProjectSchemas1).HasForeignKey(d => d.SiteAddressId);
    		this.HasOptional(t => t.OrganisationSchema).WithMany(t => t.ProjectSchemas).HasForeignKey(d => d.OrgId);
    	}
    }
}
