//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class RoleSchema
    {
        public RoleSchema()
        {
            this.InvitationSchemas = new HashSet<InvitationSchema>();
            this.MemberSchemas = new HashSet<MemberSchema>();
        }
    
        public int Id { get; set; }
        public System.Guid C_id { get; set; }
        public System.DateTime LastSvrUpdateDate { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<bool> ModifyOrg { get; set; }
        public Nullable<bool> ModifyRole { get; set; }
        public Nullable<bool> ModifyPerson { get; set; }
        public Nullable<bool> ModifyLogbook { get; set; }
        public Nullable<bool> ModifyProject { get; set; }
        public Nullable<bool> ModifyStage { get; set; }
        public Nullable<bool> ModifyMaterial { get; set; }
        public Nullable<bool> ModifyTask { get; set; }
        public Nullable<bool> ModifyTool { get; set; }
    
        public virtual ICollection<InvitationSchema> InvitationSchemas { get; set; }
        public virtual ICollection<MemberSchema> MemberSchemas { get; set; }
        public virtual OrganisationSchema OrganisationSchema { get; set; }
        public virtual ScheduleSchema ScheduleSchema { get; set; }
    }
}
