//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class RoleSchema_Mapping : EntityTypeConfiguration<RoleSchema>
    {
        public RoleSchema_Mapping()
        {					
    		this.HasKey(t => t.Id);		
    		this.ToTable("RoleSchema");
    		this.Property(t => t.Id).HasColumnName("Id");
    		this.Property(t => t.C_id).HasColumnName("_id");
    		this.Property(t => t.LastSvrUpdateDate).HasColumnName("LastSvrUpdateDate");
    		this.Property(t => t.OrganisationId).HasColumnName("OrganisationId");
    		this.Property(t => t.ScheduleId).HasColumnName("ScheduleId");
    		this.Property(t => t.Name).HasColumnName("Name").HasMaxLength(50);
    		this.Property(t => t.Description).HasColumnName("Description");
    		this.Property(t => t.Rate).HasColumnName("Rate");
    		this.Property(t => t.ModifyOrg).HasColumnName("ModifyOrg");
    		this.Property(t => t.ModifyRole).HasColumnName("ModifyRole");
    		this.Property(t => t.ModifyPerson).HasColumnName("ModifyPerson");
    		this.Property(t => t.ModifyLogbook).HasColumnName("ModifyLogbook");
    		this.Property(t => t.ModifyProject).HasColumnName("ModifyProject");
    		this.Property(t => t.ModifyStage).HasColumnName("ModifyStage");
    		this.Property(t => t.ModifyMaterial).HasColumnName("ModifyMaterial");
    		this.Property(t => t.ModifyTask).HasColumnName("ModifyTask");
    		this.Property(t => t.ModifyTool).HasColumnName("ModifyTool");
    		this.HasOptional(t => t.OrganisationSchema).WithMany(t => t.RoleSchemas).HasForeignKey(d => d.OrganisationId);
    		this.HasOptional(t => t.ScheduleSchema).WithMany(t => t.RoleSchemas).HasForeignKey(d => d.ScheduleId);
    	}
    }
}
