//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class ScheduleSchema_Mapping : EntityTypeConfiguration<ScheduleSchema>
    {
        public ScheduleSchema_Mapping()
        {					
    		this.HasKey(t => t.Id);		
    		this.ToTable("ScheduleSchema");
    		this.Property(t => t.Id).HasColumnName("Id");
    		this.Property(t => t.C_id).HasColumnName("_id");
    		this.Property(t => t.LastSvrUpdateDate).HasColumnName("LastSvrUpdateDate");
    		this.Property(t => t.RepeatDays).HasColumnName("RepeatDays").HasMaxLength(50);
    		this.Property(t => t.StartTimeMS).HasColumnName("StartTimeMS");
    		this.Property(t => t.EndTimeMS).HasColumnName("EndTimeMS");
    		this.Property(t => t.FrequencyMS).HasColumnName("FrequencyMS");
    	}
    }
}
