//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleSchema
    {
        public ScheduleSchema()
        {
            this.MemberSchemas = new HashSet<MemberSchema>();
            this.RoleSchemas = new HashSet<RoleSchema>();
            this.UserScheduleSchemas = new HashSet<UserScheduleSchema>();
        }
    
        public int Id { get; set; }
        public Nullable<System.Guid> C_id { get; set; }
        public System.DateTime LastSvrUpdateDate { get; set; }
        public string RepeatDays { get; set; }
        public Nullable<decimal> StartTimeMS { get; set; }
        public Nullable<decimal> EndTimeMS { get; set; }
        public Nullable<decimal> FrequencyMS { get; set; }
    
        public virtual ICollection<MemberSchema> MemberSchemas { get; set; }
        public virtual ICollection<RoleSchema> RoleSchemas { get; set; }
        public virtual ICollection<UserScheduleSchema> UserScheduleSchemas { get; set; }
    }
}
