//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class ServiceSchema_Mapping : EntityTypeConfiguration<ServiceSchema>
    {
        public ServiceSchema_Mapping()
        {					
    		this.HasKey(t => t.Id);		
    		this.ToTable("ServiceSchema");
    		this.Property(t => t.Id).HasColumnName("Id");
    		this.Property(t => t.C_id).HasColumnName("_id");
    		this.Property(t => t.LastSvrUpdateDate).HasColumnName("LastSvrUpdateDate");
    		this.Property(t => t.SystemName).HasColumnName("SystemName").IsRequired().HasMaxLength(50);
    		this.Property(t => t.ServiceName).HasColumnName("ServiceName").IsRequired().HasMaxLength(50);
    		this.Property(t => t.Version).HasColumnName("Version").IsRequired().HasMaxLength(50);
    		this.Property(t => t.LiveUrl).HasColumnName("LiveUrl").IsRequired().HasMaxLength(50);
    		this.Property(t => t.DevUrl).HasColumnName("DevUrl").HasMaxLength(50);
    		this.Property(t => t.TestUrl).HasColumnName("TestUrl").HasMaxLength(50);
    	}
    }
}
