//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSchema
    {
        public int Id { get; set; }
        public Nullable<System.Guid> C_id { get; set; }
        public Nullable<System.DateTime> LastSvrUpdateDate { get; set; }
        public string SystemName { get; set; }
        public string ServiceName { get; set; }
        public string Version { get; set; }
        public string LiveUrl { get; set; }
        public string DevUrl { get; set; }
        public string TestUrl { get; set; }
    }
}
