//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class StageSchema_Mapping : EntityTypeConfiguration<StageSchema>
    {
        public StageSchema_Mapping()
        {					
    		this.HasKey(t => t.Id);		
    		this.ToTable("StageSchema");
    		this.Property(t => t.Id).HasColumnName("Id");
    		this.Property(t => t.C_id).HasColumnName("_id");
    		this.Property(t => t.LastSvrUpdateDate).HasColumnName("LastSvrUpdateDate");
    		this.Property(t => t.OrgId).HasColumnName("OrgId");
    		this.Property(t => t.ProjectId).HasColumnName("ProjectId");
    		this.Property(t => t.Sequence).HasColumnName("Sequence");
    		this.Property(t => t.Description).HasColumnName("Description").HasMaxLength(100);
    		this.Property(t => t.QuotedValue).HasColumnName("QuotedValue");
    		this.Property(t => t.ShowOnQuote).HasColumnName("ShowOnQuote");
    		this.Property(t => t.EstStartDate).HasColumnName("EstStartDate");
    		this.Property(t => t.IsComplete).HasColumnName("IsComplete");
    		this.HasOptional(t => t.OrganisationSchema).WithMany(t => t.StageSchemas).HasForeignKey(d => d.OrgId);
    		this.HasOptional(t => t.ProjectSchema).WithMany(t => t.StageSchemas).HasForeignKey(d => d.ProjectId);
    	}
    }
}
