//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTek.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class TaskSchema_Mapping : EntityTypeConfiguration<TaskSchema>
    {
        public TaskSchema_Mapping()
        {					
    		this.HasKey(t => t.Id);		
    		this.ToTable("TaskSchema");
    		this.Property(t => t.Id).HasColumnName("Id");
    		this.Property(t => t.C_id).HasColumnName("_id");
    		this.Property(t => t.LastSvrUpdateDate).HasColumnName("LastSvrUpdateDate");
    		this.Property(t => t.CreatorId).HasColumnName("CreatorId");
    		this.Property(t => t.CreatedDate).HasColumnName("CreatedDate");
    		this.Property(t => t.CurrentOwnerId).HasColumnName("CurrentOwnerId");
    		this.Property(t => t.LastUpdateDate).HasColumnName("LastUpdateDate");
    		this.Property(t => t.OrganisationId).HasColumnName("OrganisationId");
    		this.Property(t => t.ProjectId).HasColumnName("ProjectId");
    		this.Property(t => t.ProjectStageId).HasColumnName("ProjectStageId");
    		this.Property(t => t.EstStartDate).HasColumnName("EstStartDate");
    		this.Property(t => t.EstHours).HasColumnName("EstHours");
    		this.Property(t => t.ActStartDate).HasColumnName("ActStartDate");
    		this.Property(t => t.ActHours).HasColumnName("ActHours");
    		this.Property(t => t.Priority).HasColumnName("Priority");
    		this.Property(t => t.Status).HasColumnName("Status").HasMaxLength(100);
    		this.Property(t => t.Title).HasColumnName("Title").HasMaxLength(100);
    		this.Property(t => t.Detail).HasColumnName("Detail").HasMaxLength(100);
    		this.Property(t => t.History).HasColumnName("History").HasMaxLength(100);
    		this.Property(t => t.NotifyNoShow).HasColumnName("NotifyNoShow");
    		this.Property(t => t.NotifyApproach).HasColumnName("NotifyApproach");
    		this.Property(t => t.MyTaskRating).HasColumnName("MyTaskRating");
    		this.Property(t => t.BossTaskRating).HasColumnName("BossTaskRating");
    		this.Property(t => t.CustTaskRating).HasColumnName("CustTaskRating");
    		this.HasOptional(t => t.OrganisationSchema).WithMany(t => t.TaskSchemas).HasForeignKey(d => d.OrganisationId);
    		this.HasOptional(t => t.ProjectSchema).WithMany(t => t.TaskSchemas).HasForeignKey(d => d.ProjectId);
    		this.HasOptional(t => t.UserSchema).WithMany(t => t.TaskSchemas).HasForeignKey(d => d.CreatorId);
    		this.HasOptional(t => t.UserSchema1).WithMany(t => t.TaskSchemas1).HasForeignKey(d => d.CurrentOwnerId);
    	}
    }
}
